=== pkrysiak/practical_work/iTunesDTD.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ENTITY % idAttribute "id ID #REQUIRED">
<!ELEMENT iTunes (Users, Tracks, Playlists) >

<!ELEMENT Users (User+) >
<!ELEMENT User (Email)>
<!ATTLIST User %idAttribute;>
<!ATTLIST User password CDATA #REQUIRED >
<!ELEMENT Email (#PCDATA) >

<!ELEMENT Tracks (Track+) >
<!ELEMENT Track (Album, Genre, Duration, Year)>
<!ATTLIST Track %idAttribute;>
<!ATTLIST Track title CDATA #REQUIRED >
<!ATTLIST Track artist CDATA #REQUIRED >
<!ELEMENT Album (#PCDATA) >
<!ELEMENT Genre (#PCDATA) >
<!ELEMENT Duration (#PCDATA) >
<!ELEMENT Year (#PCDATA) >

<!ELEMENT Playlists (Playlist+)>
<!ELEMENT Playlist (PlTracks) >
<!ATTLIST Playlist %idAttribute;>
<!ATTLIST Playlist user IDREF #REQUIRED >
<!ELEMENT PlTracks (PlTrack+) >
<!ELEMENT PlTrack (#PCDATA) >
<!ATTLIST PlTrack pltid IDREF #REQUIRED >
<!ATTLIST PlTrack title CDATA #REQUIRED >
<!ATTLIST PlTrack year CDATA #REQUIRED >

=== pkrysiak/practical_work/itunes.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE iTunes SYSTEM "iTunesDTD.dtd">
<iTunes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="iTunesSchema.xsd">
    <Users>
        <User id ="j.silver" password="asfasf">
            <Email>j.silver@hotmail.com</Email>
        </User>
        <User id = "m.anne" password="hrs362h">
            <Email>m.anne@gmail.com</Email>
        </User>
        <User id = "d.fisher" password="sgsg242">
            <Email>d.fisher@gmail.com</Email>
        </User>
    </Users>
    <Tracks>
        <Track id = "t97124" title = "Get Lucky (feat. Pharrell)" artist = "Daft Punk">
            <Album>Random Access Memories</Album>
            <Genre>Funk</Genre>
            <Duration>4:08</Duration>
            <Year>2013</Year>
        </Track>
        <Track id = "t26532" title = "Attak (feat. Danny Brown)" artist = "Rustie">
            <Album>Green Language</Album>
            <Genre>Electronic</Genre>
            <Duration>3:01</Duration>
            <Year>2014</Year>
        </Track>
        <Track id = "t15225" title = "Feels Like We Only Go Backwards" artist = "Tame Impala">
            <Album>Lonerism</Album>
            <Genre>Rock</Genre>
            <Duration>3:12</Duration>
            <Year>2012</Year>
        </Track>
        <Track id = "t58684" title = "Swimming Pools (Drank)" artist = "Kendrick Lamar">
            <Album>Good Kid, Mad City</Album>
            <Genre>Rap</Genre>
            <Duration>5:13</Duration>
            <Year>2012</Year>
        </Track>
        <Track id = "t25132" title = "Blood On The Leaves" artist = "Kanye West">
            <Album>Yeezus</Album>
            <Genre>Rap</Genre>
            <Duration>6:00</Duration>
            <Year>2013</Year>
        </Track>
    </Tracks>
    <Playlists>
        <Playlist id = "pl32535" user="j.silver">
            <PlTracks>
                <PlTrack pltid = "t97124"/>
                <PlTrack pltid = "t26532"/>
                <PlTrack pltid = "t15225"/>
                <PlTrack pltid = "t58684"/>
                <PlTrack pltid = "t25132"/>
            </PlTracks>
        </Playlist>
    </Playlists>
</iTunes>
